openocd:
    openocd -f interface/stlink.cfg -f target/stm32g4x.cfg

build:
    cargo build

clean:
    cargo clean

run:
    cargo run

attach:
    probe-rs attach --chip STM32H743ZITx ./target/thumbv7em-none-eabihf/debug/peeler_mouse
